#include $(CLEAR_VARS)
#LOCAL_MODULE := PixelLauncher
#LOCAL_MODULE_TAGS := optional
#LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
#LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_MODULE_CLASS := APPS
#LOCAL_OVERRIDES_PACKAGES := Home Launcher2 Launcher3 Launcher3QuickStep
#LOCAL_PRIVILEGED_MODULE := true
#LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
#include $(BUILD_PREBUILT)
